---
# tasks file for swarmjoin
- name: "Print Hostvars"
  debug:
    var: hostvars['manager']

- name: "Add node to swarm"
  docker_swarm:
    state: join
    advertise_addr: worker
    join_token: "{{ hostvars['mnode']['swarm_info']['swarm_facts']['JoinTokens']['instance-1'] }}"
    remote_addrs: [ 'manager:2377' ]